apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud_cd
  name: cloud_cd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud_cd
  template:
    metadata:
      labels:
        app: cloud_cd
        track: stable
    spec:
      containers:
        - image: niukor-docker.pkg.coding.net/2_devops_cicd/release/cloud_cd
          name: cloud_cd
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: coding-reporstory