apiVersion: v1
kind: Service
metadata:
  labels:
  name: cloud-service
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 8080
  selector:
    app: cloud
  type: LoadBalancer